// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

// Remove top-level await Firebase.initializeApp;
// Initialize Firebase in your main() function instead.
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5vGePleFZWoZe1oKqXwqclbQ2pJdSmWM',
    appId: '1:395687345962:web:a0222849d5c1e428a2e853',
    messagingSenderId: '395687345962',
    projectId: 'thebookread-4a4f5',
    authDomain: 'thebookread-4a4f5.firebaseapp.com',
    storageBucket: 'thebookread-4a4f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKWJ01U7n_ZpJhmi12n5OT8lN-ayGwf9Y',
    appId: '1:395687345962:android:2dfb3964c9aa2816a2e853',
    messagingSenderId: '395687345962',
    projectId: 'thebookread-4a4f5',
    storageBucket: 'thebookread-4a4f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLLZyUGu_SFToigwuiA4lWSiP1GE00kaM',
    appId: '1:395687345962:ios:2928cbffbc18f625a2e853',
    messagingSenderId: '395687345962',
    projectId: 'thebookread-4a4f5',
    storageBucket: 'thebookread-4a4f5.firebasestorage.app',
    iosBundleId: 'com.example.thebookread',
  );
}
